[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/hen1227/bluetooth-serial.git
    https://github.com/pablomarquez76/PS4_Controller_Host.git 
    
build_flags =
   -D DEBUG               ; "Funcion" para debuggear sin tener que comentar partes de codigo.
 
; ================== ENTORNOS ===============
[env:main]              ; Entorno principal

[env:prueba_bluetooth]    ; Prueba de control Bluetooth
build_src_filter = +<../test/1_bluetooth_comunication.cpp>
