[env] ; env - enviroment/entorno principal
platform = espressif32
board = esp32dev ; plaqueta a usar, usar nomenclatura de Platformio/micro
framework = arduino 
monitor_speed = 115200
; para que no compile lo que no queremos
build_flags =
    -D DEBUG